### ISSUE TITLE
cljs.reader/reader-error removed in cljs v1.9.854

### ISSUE THREAD

**Issue by petrounias** [tailrecursion/cljs-priority-map#10]
As per [https://cljs.github.io/api/cljs.reader/reader-error](https://cljs.github.io/api/cljs.reader/reader-error) the function `reader-error` was removed in version v1.9.854.

This breaks with:
`Invalid :refer, var cljs.reader/reader-error does not exist`

It is only used once at:
https://github.com/tailrecursion/cljs-priority-map/blob/605661c848e9be9dcbe207dfa6340db608ec165a/src/cljs/tailrecursion/priority_map.cljs#L186

and could be replaced with:
`(throw (js/Error. "Priority map literal expects a map for its elements."))`

As the function used to be:
`(defn reader-error
  [rdr & msg]
  (throw (js/Error. (apply str msg))))`

(e.g. from https://github.com/clojure/clojurescript/blob/e86c36bb5408a0778bde6b56a292819d6d2af4c6/src/main/cljs/cljs/reader.cljs#L70-L72 )

**Comment by va511e** [comment]
pull request created #9

**Comment by matthiasn** [comment]
Hey guys, is there anything holding back PR #9 ? Would be great if this worked again with the latest ClojureScript. Cheers, Matthias

**Comment by alandipert** [comment]
Thanks all for the reports and fix. #9 is in and 1.2.1 is deployed.
