### ISSUE TITLE
Bad require example.

### ISSUE THREAD

**Issue by rjb25** [tailrecursion/cljs-priority-map#8]
In the readme:
(ns your-ns
  (:require [tailrecursion.priority-map :refer [priority-map priority-map-by])))
Should be:
(ns your-ns
  (:require [tailrecursion.priority-map :refer [priority-map priority-map-by]]))
a parenthesis at the end should be a closing bracket

**Comment by alandipert** [comment]
Thanks for the report. This was recently fixed.
